# Generated by Django 3.2.20 on 2024-01-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
